name: StackDump
version: 0.3.1
main: me.nexodus.stackdump.StackDumpPlugin
api-version: '1.20'
description: This plugin adds a quality of life utility to dump all the stacks of an item into a chest/barrel.
